
GRANT UNLIMITED TABLESPACE TO DBTOOLS ;
grant create job to DBTOOLS ;
grant select on dba_external_tables to DBTOOLS ;
grant select on dba_external_locations to DBTOOLS ;
grant select on dba_registry to DBTOOLS ;
grant select on dba_tab_privs to DBTOOLS;
grant select on dba_tables to DBTOOLS;
grant execute on dbms_logmnr to DBTOOLS ;
grant select on sys.v_$logmnr_contents to DBTOOLS ;
grant select on sys.v_$database to DBTOOLS ;
grant select on sys.v_$session to DBTOOLS;
grant select on dba_db_links to DBTOOLS;
grant select on dba_users to DBTOOLS;
grant execute on sys.dbms_aq to DBTOOLS ;
grant execute on dbms_lock to DBTOOLS ;
grant execute on dbms_stats to DBTOOLS ;
grant create any table to DBTOOLS ;
grant select any table to DBTOOLS ;
grant drop any table to DBTOOLS;
GRANT EXECUTE ON SYS.DBMS_TRANSACTION TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_STATS TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_TRANSACTION TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DBTOOLS ;
GRANT EXECUTE ON SYS.DBMS_XA TO DBTOOLS ;
GRANT SELECT ON SYS.ALL_MVIEWS to DBTOOLS ;
GRANT SELECT ON SYS.V_$DATABASE TO DBTOOLS ;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO DBTOOLS ;
GRANT SELECT ON SYS.V_$DATABASE TO DBTOOLS ;
grant select on sys.v_$services to DBTOOLS;
grant execute on dbms_logmnr to DBTOOLS ;
grant select on sys.v_$logmnr_contents to DBTOOLS ;
grant select on sys.v_$instance to DBTOOLS ;
grant read,write on directory DB_DUMP to DBTOOLS;
grant select on sys.dba_directories to DBTOOLS;
