-- USER SQL
CREATE USER "HR_DATA" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "HR_DATA" QUOTA UNLIMITED ON "DATA";

-- ROLES
GRANT "RESOURCE" TO "HR_DATA" ;
ALTER USER "HR_DATA" DEFAULT ROLE "RESOURCE";

-- SYSTEM PRIVILEGES
GRANT ALTER SESSION TO "HR_DATA" ;
GRANT CREATE VIEW TO "HR_DATA" ;
GRANT CREATE SESSION TO "HR_DATA" ;
GRANT CREATE SYNONYM TO "HR_DATA" ;
GRANT CREATE SEQUENCE TO "HR_DATA" ;
GRANT CREATE DATABASE LINK TO "HR_DATA" ;
GRANT UNLIMITED TABLESPACE TO "HR_DATA" ;
