-- USER SQL
CREATE USER "HR_LOGIK" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "HR_LOGIK" QUOTA UNLIMITED ON "DATA";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "HR_LOGIK" ;
GRANT CREATE SESSION TO "HR_LOGIK" ;
GRANT CREATE TYPE TO "HR_LOGIK" ;
GRANT CREATE PROCEDURE TO "HR_LOGIK" ;
