-- USER SQL
CREATE USER "HR" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "HR" QUOTA UNLIMITED ON "DATA";

-- ROLES
GRANT "RESOURCE" TO "HR" ;
ALTER USER "HR" DEFAULT ROLE "RESOURCE";

-- SYSTEM PRIVILEGES
GRANT ALTER SESSION TO "HR" ;
GRANT CREATE VIEW TO "HR" ;
GRANT CREATE SESSION TO "HR" ;
GRANT CREATE SYNONYM TO "HR" ;
GRANT CREATE SEQUENCE TO "HR" ;
GRANT CREATE DATABASE LINK TO "HR" ;
GRANT UNLIMITED TABLESPACE TO "HR" ;
