- name: collect
  hosts: db_nodes
  serial: 1

  tasks:

      - name: create file
        file:
           dest: ./instance.log
           state: touch
        delegate_to: localhost

      - name: Run collect and echo output
        shell: "cat /etc/oratab |grep -e '^[^#]'|awk -F':' '{print $1}'"
        register: out

      - name: append
        lineinfile:
          dest: ./instance.log
          line: "{{ out }}"
          insertafter: EOF
        delegate_to: localhost 
