-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "DBAUDIT_LOGIK" ;
GRANT CREATE SESSION TO "DBAUDIT_LOGIK" ;
GRANT CREATE TYPE TO "DBAUDIT_LOGIK" ;
GRANT CREATE SYNONYM TO "DBAUDIT_LOGIK" ;
GRANT CREATE PROCEDURE TO "DBAUDIT_LOGIK" ;
GRANT SELECT ON SYS.DBA_ROLES TO "DBAUDIT_LOGIK";
GRANT SELECT ON SYS.DBA_TAB_PRIVS TO "DBAUDIT_LOGIK";
GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO "DBAUDIT_LOGIK";
GRANT SELECT ON SYS.DBA_OBJECTS TO "DBAUDIT_LOGIK";
GRANT SELECT ON SYS.DBA_USERS TO "DBAUDIT_LOGIK" ;
GRANT SELECT ON SYS.audit_unified_policies TO "DBAUDIT_LOGIK" ;
GRANT GRANT ANY OBJECT PRIVILEGE TO "DBAUDIT_LOGIK";
GRANT EXECUTE ON DBMS_APPLICATION_INFO TO "DBAUDIT_LOGIK";
GRANT CREATE ROLE TO "DBAUDIT_LOGIK";
GRANT AUDIT_ADMIN TO "DBAUDIT_LOGIK";
GRANT AUDIT SYSTEM TO "DBAUDIT_LOGIK";
GRANT CREATE JOB TO "DBAUDIT_LOGIK" ;
grant execute on dbms_audit_mgmt to "DBAUDIT_LOGIK";
