-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "DBAUDIT_DATA" ;
GRANT CREATE TABLE TO "DBAUDIT_DATA" ;
GRANT CREATE PROCEDURE TO "DBAUDIT_DATA" ;
GRANT SELECT ON SYS.DBA_DIRECTORIES TO "DBAUDIT_DATA" ;
GRANT SELECT ON SYS.DBA_TAB_PRIVS TO "DBAUDIT_DATA" ;
GRANT SELECT ON SYS.DBA_EXTERNAL_TABLES TO "DBAUDIT_DATA" ;
GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO "DBAUDIT_DATA" ;
GRANT CREATE ANY DIRECTORY TO "DBAUDIT_DATA" ;
GRANT GRANT ANY PRIVILEGE TO "DBAUDIT_DATA" ;
