BEGIN
      DBMS_SCHEDULER.enable(name=>'"DBAUDIT_LOGIK"."AUTO_AUDIT_NEW_OBJS"');
END;
/

BEGIN
      DBMS_SCHEDULER.enable(name=>'"DBAUDIT_LOGIK"."AUTO_PURGE_UNIFIED_AUDIT_TRAIL"');
END;
/

BEGIN
      DBMS_SCHEDULER.enable(name=>'"DBAUDIT_LOGIK"."AUTO_AUDIT_MAINTENANCE"');
END;
/

BEGIN
      DBMS_SCHEDULER.enable(name=>'"DBAUDIT_LOGIK"."AUTO_PURGE_AUDIT_TRAIL_MAINTENANCE"');
END;
/